apiVersion: v1
kind: ConfigMap
metadata:
  name: restapi-user-configmap
data:
  POSTGRESS_DB: $POSTGRESS_DB
  POSTGRESS_HOST: $POSTGRESS_HOST
  AWS_REGION: $AWS_REGION
  AWS_PROFILE: $AWS_PROFILE
  AWS_BUCKET: $AWS_BUCKET
