apiVersion: v1
kind: Secret
metadata:
  name: restapi-user-secret
stringData:
  POSTGRES_USERNAME: {{POSTGRES_USERNAME}}
  POSTGRES_PASSWORD: {{POSTGRES_PASSWORD}}
  POSTGRES_DB: {{POSTGRES_DB}}
  POSTGRES_HOST: {{POSTGRES_HOST}}
  JWT_SECRET: {{JWT_SECRET}}
