apiVersion: v1
kind: Pod
metadata:
  name: restapi-feed
spec:
  containers:
    - image: registry:5000/restapi-feed
      name: restapi-feed
      imagePullPolicy: Always
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "1024Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: restapi-feed-configmap
        - secretRef:
            name: restapi-feed-secret
  restartPolicy: Always
